spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=catalog
spring.application.name=catalog
spring.cloud.config.profile=local
management.endpoints.web.exposure.include=*