spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=sales
spring.cloud.config.profile=local
spring.application.name=sales
management.endpoints.web.exposure.include=*