spring.application.name=eurekaserver
server.port=${SERVER_PORT:8761}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.renewal-percent-threshold=0.80
eureka.instance.lease-renewal-interval-in-seconds=300
eureka.server.enable-self-preservation=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true