spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=purchases
spring.application.name=purchases
spring.cloud.config.profile=local
management.endpoints.web.exposure.include=*