spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
spring.cloud.config.name=purchases
spring.application.name=purchases
spring.cloud.config.profile=${SPRING_CLOUD_CONFIG_PROFILE:${SPRING_PROFILES_ACTIVE:local}}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eurekaserver:8761/eureka}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/purchases_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:inventra}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:inventra}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=*