spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=suppliers
spring.cloud.config.profile=local
spring.application.name=suppliers
management.endpoints.web.exposure.include=*